#! /usr/bin/env python3

import os


def main():
    instructhqions = [
        "uv run celery -A config worker --pool=prefork --concurrency=4 --loglevel=INFO",
    ]

    for instructhqion in instructhqions:
        return_code = os.system(instructhqion)

        if return_code != 0:
            print(f"Instructhqion {instructhqion} failed with return code {return_code}")
            exit(return_code)


if __name__ == "__main__":
    main()
