#!/usr/bin/env python3

import argparse
import os
from enum import Enum


class Command(Enum):
    create = "create"
    drop = "drop"

    def __str__(self):
        return self.value


parser = argparse.ArgumentParser(description="Util for managing development database")
parser.add_argument("command", type=Command, choices=list(Command))

args = parser.parse_args()


def create_db():
    os.system(
        'PGPASSWORD=postgres psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = \'structhq_development\'" \
        | grep -q 1 \
        || PGPASSWORD=postgres psql -U postgres -c "CREATE DATABASE structhq_development"'
    )


def drop_db():
    os.system('PGPASSWORD=postgres psql -U postgres -tc "DROP DATABASE IF EXISTS structhq_development"')


def main():
    if args.command == Command.create:
        create_db()
        return

    if args.command == Command.drop:
        drop_db()
        return


if __name__ == "__main__":
    main()
