# Generated by Django 5.1 on 2024-12-30 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structhq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('data_schema', models.JSONField(blank=True, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='struct_requests', to='structhq.profile')),
            ],
            options={
                'verbose_name': 'Struct Request',
                'verbose_name_plural': 'Struct Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StructRequestMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField()),
                ('message_type', models.TextField(choices=[('user_text', 'User Text'), ('assistant_text', 'Assistant Text'), ('assistant_tool_call', 'Assistant Tool Call'), ('assistant_tool_response', 'Assistant Tool Response')])),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='structhq.structrequest')),
            ],
            options={
                'verbose_name': 'Struct Request Message',
                'verbose_name_plural': 'Struct Request Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
