# Generated by Django 5.1 on 2024-12-30 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structhq', '0002_structrequest_structrequestmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structrequestmessage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='structhq.structrequest'),
        ),
    ]
