# Generated by Django 5.1 on 2025-01-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structhq', '0004_structrequestmessage_tool_calls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structrequestmessage',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
