# Generated by Django 5.1 on 2025-01-02 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structhq', '0005_alter_structrequestmessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structrequestmessage',
            name='request',
        ),
        migrations.CreateModel(
            name='StructRequestChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='structhq.structrequest')),
            ],
            options={
                'verbose_name': 'Struct Request Chunk',
                'verbose_name_plural': 'Struct Request Chunks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='structrequestmessage',
            name='chunk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='structhq.structrequestchunk'),
            preserve_default=False,
        ),
    ]
