# Generated by Django 5.1 on 2025-01-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structhq', '0006_remove_structrequestmessage_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structrequestchunk',
            name='chunk',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
